
services:
  notas_ventas:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://notas_ventasbd:3306/notas_ventas?createDatabaseIfNotExist=true&serverTimezone=UTC
      DB_USER_NAME: root
      DB_PASSWORD: 1234
    restart: always
    depends_on:
      notas_ventasbd:
        condition: service_healthy
  notas_ventasbd:
    image: mysql:8.0.33
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: notas_ventas
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10